version: '3.8'

volumes:
  bundler-config:
  bundler-gems:

services:
  inst_access:
    build:
      context: .
    volumes:
      - bundler-config:/home/docker/.bundle
      - bundler-gems:/home/docker/.gem/ruby
